# Creating More Functions

## Proposed Resolution

## Task 1

In this task, I used Python's built-in `sorted()` function to order the `failed_login_list` from smallest to largest. By passing the call to the `sorted()` function directly into the `print()` function, I was able to display and examine the sorted result.

I was provided a list of the number of failed login attempts per month, which are as follows: 

`119`, `101`, `99`, `91`, `92`, `105`, `108`, `85`, `88`, `90`, `264`, and `223`.

This list is organized in chronological order of months (January, February, March, April, May, June, July, August, September, October, November, and December).

This list is stored in a variable named `failed_login_list`. 


In [1]:
# Assign `failed_login_list` to the list of the number of failed login attempts per month 

failed_login_list = [119, 101, 99, 91, 92, 105, 108, 85, 88, 90, 264, 223]

# Sort `failed_login_list` in ascending numerical order and display the result

print(sorted(failed_login_list))


[85, 88, 90, 91, 92, 99, 101, 105, 108, 119, 223, 264]


#### **Question 1**
**What do you observe from the output above? Do you notice any outlying numbers that indicate an increase in the failed number of login attempts?**

The output above shows that the function call to `sorted()` sorted the `failed_login_list` in ascending numerical order. The outputted list starts with the lowest number of failed login attempts and ends with the highest number of failed login attempts. The last two numbers in the sorted list (223 and 264) seem to be outlying numbers, indicating an increase in the number of failed login attempts.

## Task 2

I used the `max()` function to isolate the highest number of failed login attempts from the list. I passed the `failed_login_list` into the function and then used the `print()` function to display the result. This allowed me to identify the month with the highest number of failed login attempts for further investigation.


In [2]:
# Assign `failed_login_list` to the list of the number of failed login attempts per month 

failed_login_list = [119, 101, 99, 91, 92, 105, 108, 85, 88, 90, 264, 223]

# Determine the highest number of failed login attempts from `failed_login_list` and display the result 

print(max(failed_login_list))


264


#### **Question 2**
**What do you observe from the output above?**

The output above shows that the function call to `max()` isolated the highest number from the `failed_login_list`. The highest number of failed login attempts was 264.

## Task 3

I defined the function `analyze_logins()` that takes in two parameters: `username` and `current_day_logins`. Inside the function, I wrote code that displays a message about the number of login attempts the user has made on that particular day. Since this is just a function definition, running the cell won't produce an output yet.


In [3]:
# Define a function named `analyze_logins()` that takes in two parameters, `username` and `current_day_logins`  

def analyze_logins(username, current_day_logins):

    # Display a message about how many login attempts the user has made that day

    print("Current day login total for", username, "is", current_day_logins)
    

## Task 4

I called the `analyze_logins()` function with the arguments `"ejones"` and `9`. This resulted in a message being displayed that provided information about the 9 login attempts made by the user `"ejones"` on that particular day.


In [4]:
# Define a function named `analyze_logins()` that takes in two parameters, `username` and `current_day_logins` 

def analyze_logins(username, current_day_logins):

    # Display a message about how many login attempts the user has made that day

    print("Current day login total for", username, "is", current_day_logins)

# Call `analyze_logins()` 

analyze_logins("ejones", 9)


Current day login total for ejones is 9


#### **Question 3**
**What does this function display? Would the output vary for different users?**

This function displays the message `"Current day login total for ejones is 9"` when the arguments are `"ejones"` and `9`. The function is defined in a way that's specific to the user, so it would produce a different output for a different user.

## Task 5

I expanded the `analyze_logins()` function by adding a third parameter called `average_day_logins`. This parameter helps display an additional message that conveys the average login attempts made by the user on that day.

I then called the function with the arguments `"ejones"`, `9`, and `3`. This resulted in a message being displayed that provided both the total number of login attempts (9) and the average number of login attempts (3) made by the user `"ejones"` on that day.


In [1]:
# Define a function named `analyze_logins()` that takes in three parameters, `username`, `current_day_logins`, and `average_day_logins`

def analyze_logins(username, current_day_logins, average_day_logins):

    # Display a message about how many login attempts the user has made that day

    print("Current day login total for", username, "is", current_day_logins)
    
    # Display a message about average number of login attempts the user has made that day 
    
    print("Average logins per day for", username, "is", average_day_logins)

# Call `analyze_logins()` 

analyze_logins("ejones", 9, 3)


Current day login total for ejones is 9
Average logins per day for ejones is 3


## Task 6

I expanded the `analyze_logins()` function by adding a new calculation to determine the ratio of the logins made on the current day to the logins made on an average day. I stored this ratio in a variable named `login_ratio`.

Additionally, I included a new message that displays this `login_ratio`.

After defining the function, I called it with the same arguments as before: `"ejones"`, `9`, and `3`. The function displayed messages about the total login attempts, average login attempts, and the calculated login ratio.

In [6]:
# Define a function named `analyze_logins()` that takes in three parameters, `username`, `current_day_logins`, and `average_day_logins`

def analyze_logins(username, current_day_logins, average_day_logins):

    # Display a message about how many login attempts the user has made that day

    print("Current day login total for", username, "is", current_day_logins)
    
    # Display a message about average number of login attempts the user has made that day 
    
    print("Average logins per day for", username, "is", average_day_logins)
    
    # Calculate the ratio of the logins made on the current day to the logins made on an average day, storing in a variable named `login_ratio`
    
    login_ratio = current_day_logins / average_day_logins
    
    # Display a message about the ratio
    
    print(username, "logged in", login_ratio, "times as much as they do on an average day.")

# Call `analyze_logins()` 

analyze_logins("ejones", 9, 3)


Current day login total for ejones is 9
Average logins per day for ejones is 3
ejones logged in 3.0 times as much as they do on an average day.


#### **Question 4**
**What does this version of the `analyze_logins()` function display? Would the output vary for different users?**

This version of the `analyze_logins()` function displays a user's current day login total, average logins per day, and ratio of current day login total to average logins per day. It produces a distinct output for each distinct username that it takes in.

## Task 7

I modified the `analyze_logins()` function by adding a `return` statement that outputs the `login_ratio` from the function. This allows the `login_ratio` to be used later in my work.

I called the function with the same arguments as before: `"ejones"`, `9`, and `3`. I stored the result of the function call in a variable named `login_analysis`. Finally, I used a `print()` statement to display the `login_analysis` value, which contains the calculated login ratio.


In [7]:
# Define a function named `analyze_logins()` that takes in three parameters, `username`, `current_day_logins`, and `average_day_logins`

def analyze_logins(username, current_day_logins, average_day_logins):

    # Display a message about how many login attempts the user has made that day

    print("Current day login total for", username, "is", current_day_logins)
    
    # Display a message about average number of login attempts the user has made that day 
    
    print("Average logins per day for", username, "is", average_day_logins)
    
    # Calculate the ratio of the logins made on the current day to the logins made on an average day, storing in a variable named `login_ratio`
    
    login_ratio = current_day_logins / average_day_logins
    
    # Return the ratio
    
    return login_ratio

# Call `analyze_logins() and store the output in a variable named `login_analysis` 

login_analysis = analyze_logins("ejones", 9, 3)
    
# Display a message about the `login_analysis`

print("ejones", "logged in", login_analysis, "times as much as they do on an average day.")


Current day login total for ejones is 9
Average logins per day for ejones is 3
ejones logged in 3.0 times as much as they do on an average day.


#### **Question 5**
**How does this version of the `analyze_logins()` function compare to the previous versions?**

This version of the `analyze_logins()` function involves a `return` statement instead of a `print()` statement, which allows you to store the output from the function call in a variable for later usage.

## Task 8

I incorporated the conditional statement to check the value of `login_analysis`. When the `login_analysis` value is greater than or equal to `3`, I displayed an alert message indicating that the login activity requires further investigation. This condition ensures that high login activity is flagged for review. 


In [8]:
# Define a function named `analyze_logins()` that takes in three parameters, `username`, `current_day_logins`, and `average_day_logins`

def analyze_logins(username, current_day_logins, average_day_logins):

    # Display a message about how many login attempts the user has made that day

    print("Current day login total for", username, "is", current_day_logins)
    
    # Display a message about average number of login attempts the user has made that day 
    
    print("Average logins per day for", username, "is", average_day_logins)
    
    # Calculate the ratio of the logins made on the current day to the logins made on an average day, storing in a variable named `login_ratio`
    
    login_ratio = current_day_logins / average_day_logins
    
    # Return the ratio
    
    return login_ratio

# Call `analyze_logins() and store the output in a variable named `login_analysis` 

login_analysis = analyze_logins("ejones", 9, 3)

# Conditional statement that displays an alert about the login activity if it's more than normal

if login_analysis >= 3:
    print("Alert! This account has more login activity than normal.")
    

Current day login total for ejones is 9
Average logins per day for ejones is 3
Alert! This account has more login activity than normal.


## Conclusion

**What are your key takeaways from this lab?**

- There are a variety of ways a function can be written. 
  - It can be written to display information to the screen, or return information that can then be saved in a variable.
  - Also it can be written to take in any number of parameters, use the parameters to execute a series of tasks, and then return a result.
- The `sorted()` function in Python is a built-in function that helps me sort the components of a list.
  - For example, when I call `sorted()` with a list of numbers, it returns the list with the elements in numerical order. 
- The `max()` function in Python is a built-in function that helps me identify the element with the maximum value in a list. 
  - For example, when I call `max()` with a list of numbers, it returns the largest number in the list. 
- The `print()` function in Python is a built-in function that helps display information. It can also be used to directly display the output from another function call. 
  - To display the output from another function call, make sure to place it inside a `print()` statement.